name: my-check
on: push
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: my-step
        run: echo "Check"
      - name: Lint
        run: make lint
      - name: Testing
        run: make tests