name: my-check
on: push
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: |
          pip install poetry
          make install build publish package-reinstall
      - name: Run linter and pytest
        run: |
          make lint test