name: my-check
on: push
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: init project
        run: make install build publish package-reinstall
      - name: Lint
        run: make lint
      - name: Testing
        run: make test